import type { DistractionMeta } from '../types/distraction';

export const DISTRACTIONS: DistractionMeta[] = [
  {
    id: 'reaction-test',
    index: 1,
    title: 'Reaction Test',
    codename: 'REFLEX PROTOCOL',
    category: 'Reflex',
    difficulty: 'EASY',
    description: 'Intercept high-priority signal. Click target instantly when the signal triggers.',
    objective: 'Click as fast as possible when target turns active. False starts penalize.',
    icon: 'Zap',
    targetRequirement: 'Reaction Time < 450ms',
    estimatedSeconds: 8,
  },
  {
    id: 'memory-match',
    index: 2,
    title: 'Memory Match',
    codename: 'SYNAPSE MATRIX',
    category: 'Memory',
    difficulty: 'MEDIUM',
    description: 'Neural pattern encryption. Re-link 6 paired cyber modules before memory decay.',
    objective: 'Match all 6 pairs of cyber nodes. Initial peek preview provided.',
    icon: 'Layers',
    targetRequirement: 'Match 6/6 Pairs',
    estimatedSeconds: 25,
  },
  {
    id: 'quick-math',
    index: 3,
    title: 'Quick Math',
    codename: 'ALGO ARITHMETIC',
    category: 'Speed',
    difficulty: 'MEDIUM',
    description: 'Solve fast arithmetic and logic operations under high-speed tournament clock.',
    objective: 'Solve 4 consecutive arithmetic equations accurately.',
    icon: 'Calculator',
    targetRequirement: '4 Correct Solutions',
    estimatedSeconds: 15,
  },
  {
    id: 'color-trap',
    index: 4,
    title: 'Color Trap',
    codename: 'STROOP OVERLOAD',
    category: 'Cognitive',
    difficulty: 'HARD',
    description: 'Cognitive conflict disruptor. Disregard text semantic meaning and target font colors.',
    objective: 'Select target color according to dynamic protocol (Color vs Word).',
    icon: 'Eye',
    targetRequirement: '5 Correct Strikes',
    estimatedSeconds: 18,
  },
  {
    id: 'pattern-puzzle',
    index: 5,
    title: 'Pattern Puzzle',
    codename: 'SEQUENCE LOGIC',
    category: 'Logic',
    difficulty: 'MEDIUM',
    description: 'Detect binary, geometric, and numerical pattern progression.',
    objective: 'Determine the missing element in 3 logical sequence equations.',
    icon: 'Cpu',
    targetRequirement: '3 Correct Sequences',
    estimatedSeconds: 22,
  },
  {
    id: 'odd-one-out',
    index: 6,
    title: 'Odd One Out',
    codename: 'ANOMALY DETECTOR',
    category: 'Cognitive',
    difficulty: 'MEDIUM',
    description: 'Scan glyph grid to isolate defective rogue node with subtle orientation or syntax anomaly.',
    objective: 'Identify and tap the anomalous cell across 3 tactical radar scans.',
    icon: 'Crosshair',
    targetRequirement: '3 Anomalies Cleared',
    estimatedSeconds: 20,
  },
  {
    id: 'simon-says',
    index: 7,
    title: 'Simon Says',
    codename: 'NEURAL SEQUENCE',
    category: 'Memory',
    difficulty: 'HARD',
    description: 'Decode and repeat audio-visual impulse sequences across quad-core nodes.',
    objective: 'Repeat 3 escalating neural impulse sequences accurately.',
    icon: 'Activity',
    targetRequirement: 'Complete Level 3 (5 Notes)',
    estimatedSeconds: 30,
  },
  {
    id: 'trivia-blitz',
    index: 8,
    title: 'Trivia Blitz',
    codename: 'TECH ARCHIVES',
    category: 'Cognitive',
    difficulty: 'EASY',
    description: 'Fast-paced computer science, algorithm history, and system trivia verification.',
    objective: 'Answer at least 4 out of 5 tech trivia questions correctly.',
    icon: 'HelpCircle',
    targetRequirement: 'Score ≥ 4 / 5',
    estimatedSeconds: 25,
  },
  {
    id: 'typing-challenge',
    index: 9,
    title: 'Typing Challenge',
    codename: 'TERMINAL INJECTION',
    category: 'Speed',
    difficulty: 'HARD',
    description: 'Inject secure authentication command code with zero syntax errors.',
    objective: 'Type the code command accurately with ≥ 90% accuracy.',
    icon: 'Terminal',
    targetRequirement: 'Accuracy ≥ 90%',
    estimatedSeconds: 20,
  },
  {
    id: 'catch-object',
    index: 10,
    title: 'Catch The Object',
    codename: 'PACKET INTERCEPTOR',
    category: 'Reflex',
    difficulty: 'MEDIUM',
    description: 'Rogue data packets are breaching the firewall. Intercept them before dissipation.',
    objective: 'Click/tap 8 rogue packets before they expire.',
    icon: 'Radio',
    targetRequirement: '8 Intercepts Captured',
    estimatedSeconds: 18,
  },
];
