-- Migration: 005_core_schema.sql
-- Description: Core competition schema — event config, languages, problems + hidden tests,
--              participations, per-round attempts, submissions, distraction log and proctoring alerts.
--
-- Access model: the FastAPI backend connects as the `postgres` role (bypasses RLS) and is the only
-- writer. RLS is enabled on every table with NO policies for anon/authenticated, so the Supabase
-- REST API cannot read hidden test cases or tamper with scores. The one exception is `event_config`,
-- which authenticated users may SELECT so the frontend can subscribe to Realtime status changes.

-- ---------------------------------------------------------------------------
-- 0. Security fix: never trust a client-supplied role on sign-up.
--    Previously `raw_user_meta_data->>'role' = 'admin'` made any visitor an admin.
--    Admins are now promoted server-side (see `python -m app.cli make-admin <email>`).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
        'participant'
    )
    ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        full_name = EXCLUDED.full_name;

    UPDATE auth.users
    SET raw_app_meta_data = COALESCE(raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('role', 'participant')
    WHERE id = NEW.id;

    RETURN NEW;
END;
$$;

-- Stable, human-friendly player number (CAD-0001 ...). Backfills existing rows.
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS player_no INTEGER GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_player_no ON public.profiles(player_no);

-- ---------------------------------------------------------------------------
-- 1. Enums
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE event_status AS ENUM ('lobby', 'live', 'ended');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE participant_status AS ENUM ('joined', 'playing', 'finished');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE round_status AS ENUM ('active', 'solved', 'expired');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ---------------------------------------------------------------------------
-- 2. Event configuration (singleton row)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.event_config (
    id                    BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    name                  TEXT        NOT NULL DEFAULT 'Ctrl Alt Distract',
    organizer_name        TEXT        NOT NULL,
    college_name          TEXT        NOT NULL,
    scheduled_at          TIMESTAMPTZ NOT NULL,
    timezone              TEXT        NOT NULL DEFAULT 'Asia/Kolkata',
    timezone_label        TEXT        NOT NULL DEFAULT 'IST',
    total_rounds          INTEGER     NOT NULL DEFAULT 10 CHECK (total_rounds > 0),
    round_seconds         INTEGER     NOT NULL DEFAULT 600 CHECK (round_seconds > 0),
    dsa_points            INTEGER     NOT NULL DEFAULT 100,
    bonus_points          INTEGER     NOT NULL DEFAULT 50,
    distraction_seconds   INTEGER     NOT NULL DEFAULT 30,
    distraction_grace_seconds INTEGER NOT NULL DEFAULT 15,
    distraction_min_at    INTEGER     NOT NULL DEFAULT 180,
    distraction_max_at    INTEGER     NOT NULL DEFAULT 300,
    status                event_status NOT NULL DEFAULT 'lobby',
    started_at            TIMESTAMPTZ,
    ended_at              TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (distraction_min_at <= distraction_max_at)
);

INSERT INTO public.event_config (organizer_name, college_name, scheduled_at)
VALUES (
    'GDG on Campus Vidyalankar Institute of Technology',
    'Vidyalankar Institute of Technology',
    TIMESTAMPTZ '2026-10-18 10:00:00+05:30'
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Supported languages (Judge0 ids are the Judge0 CE defaults; override per deployment if needed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.languages (
    id               TEXT PRIMARY KEY,           -- python | cpp | c | java
    label            TEXT    NOT NULL,
    filename         TEXT    NOT NULL,           -- name shown in the editor tab / compiler messages
    judge0_id        INTEGER NOT NULL,
    time_multiplier  NUMERIC(4,1) NOT NULL DEFAULT 1,
    ord              INTEGER NOT NULL,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO public.languages (id, label, filename, judge0_id, time_multiplier, ord) VALUES
    ('python', 'Python', 'solution.py',   71, 3, 1),
    ('cpp',    'C++',    'solution.cpp',  54, 1, 2),
    ('c',      'C',      'solution.c',    50, 1, 3),
    ('java',   'Java',   'Solution.java', 62, 2, 4)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Problems and test cases
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.problems (
    id              SERIAL PRIMARY KEY,
    round_no        INTEGER NOT NULL UNIQUE CHECK (round_no > 0),
    slug            TEXT    NOT NULL UNIQUE,
    title           TEXT    NOT NULL,
    difficulty      TEXT    NOT NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    tags            TEXT[]  NOT NULL DEFAULT '{}',
    description     JSONB   NOT NULL DEFAULT '[]',      -- array of paragraphs
    input_format    TEXT    NOT NULL DEFAULT '',
    output_format   TEXT    NOT NULL DEFAULT '',
    examples        JSONB   NOT NULL DEFAULT '[]',      -- [{input, output, explanation}]
    constraints     TEXT[]  NOT NULL DEFAULT '{}',
    hints           TEXT[]  NOT NULL DEFAULT '{}',
    signature       JSONB   NOT NULL,                   -- {function, params:[{name,type}], returns}
    time_limit_ms   INTEGER NOT NULL DEFAULT 1500,      -- per test case, before the language multiplier
    memory_limit_kb INTEGER NOT NULL DEFAULT 262144,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.problem_tests (
    id               BIGSERIAL PRIMARY KEY,
    problem_id       INTEGER NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    ord              INTEGER NOT NULL,
    stdin            TEXT    NOT NULL,                  -- one case in the harness wire format
    expected         TEXT    NOT NULL,                  -- expected output line
    is_sample        BOOLEAN NOT NULL DEFAULT FALSE,    -- samples are used by RUN and shown to players
    display_input    TEXT,
    display_expected TEXT,
    UNIQUE (problem_id, ord)
);
CREATE INDEX IF NOT EXISTS idx_problem_tests_problem ON public.problem_tests(problem_id, ord);

-- ---------------------------------------------------------------------------
-- 5. Participation and per-round progress
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.participations (
    user_id              UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    status               participant_status NOT NULL DEFAULT 'joined',
    joined_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at           TIMESTAMPTZ,
    finished_at          TIMESTAMPTZ,
    current_round        INTEGER NOT NULL DEFAULT 0,
    distraction_order    INTEGER[] NOT NULL,            -- per-player shuffled distraction indices
    round_pts            INTEGER NOT NULL DEFAULT 0,
    bonus_pts            INTEGER NOT NULL DEFAULT 0,
    total_pts            INTEGER GENERATED ALWAYS AS (round_pts + bonus_pts) STORED,
    total_time_ms        BIGINT  NOT NULL DEFAULT 0,
    solved_count         INTEGER NOT NULL DEFAULT 0,
    distractions_total   INTEGER NOT NULL DEFAULT 0,
    distractions_cleared INTEGER NOT NULL DEFAULT 0,
    active_client        TEXT,                           -- tab/device id, used to flag multi-session play
    last_seen_at         TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_participations_rank
    ON public.participations (total_pts DESC, total_time_ms ASC, joined_at ASC);
CREATE INDEX IF NOT EXISTS idx_participations_status ON public.participations(status);

CREATE TABLE IF NOT EXISTS public.round_attempts (
    user_id           UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    round_no          INTEGER NOT NULL,
    problem_id        INTEGER NOT NULL REFERENCES public.problems(id),
    status            round_status NOT NULL DEFAULT 'active',
    started_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at       TIMESTAMPTZ,
    paused_ms         INTEGER NOT NULL DEFAULT 0,       -- time spent inside distractions (timer is frozen)
    pause_started_at  TIMESTAMPTZ,
    submit_lock_until TIMESTAMPTZ,                      -- set while a submission is being judged; blocks expiry
    time_ms           INTEGER,                          -- active time used, set when resolved
    points            INTEGER NOT NULL DEFAULT 0,
    bonus             INTEGER NOT NULL DEFAULT 0,
    distraction_index INTEGER NOT NULL,
    distraction_at    INTEGER NOT NULL,                 -- active seconds into the round when it fires
    distraction_state TEXT    NOT NULL DEFAULT 'pending'
        CHECK (distraction_state IN ('pending', 'active', 'cleared', 'missed')),
    PRIMARY KEY (user_id, round_no)
);
CREATE INDEX IF NOT EXISTS idx_round_attempts_status ON public.round_attempts(status);

CREATE TABLE IF NOT EXISTS public.submissions (
    id           BIGSERIAL PRIMARY KEY,
    user_id      UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    problem_id   INTEGER NOT NULL REFERENCES public.problems(id),
    round_no     INTEGER NOT NULL,
    language     TEXT    NOT NULL REFERENCES public.languages(id),
    kind         TEXT    NOT NULL CHECK (kind IN ('run', 'submit')),
    code         TEXT    NOT NULL,
    verdict      TEXT    NOT NULL,                      -- accepted | wrong | compile-error | passed | failed | expired
    passed       INTEGER NOT NULL DEFAULT 0,
    total        INTEGER NOT NULL DEFAULT 0,
    runtime_ms   INTEGER,
    memory_kb    INTEGER,
    detail       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_submissions_user ON public.submissions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_problem ON public.submissions(problem_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.distraction_events (
    id                BIGSERIAL PRIMARY KEY,
    user_id           UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    round_no          INTEGER NOT NULL,
    distraction_index INTEGER NOT NULL,
    distraction_id    TEXT,
    result            TEXT    NOT NULL CHECK (result IN ('passed', 'failed', 'timeout')),
    time_taken        INTEGER,
    bonus             INTEGER NOT NULL DEFAULT 0,
    metrics           JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_distraction_events_user ON public.distraction_events(user_id, round_no);

-- ---------------------------------------------------------------------------
-- 6. Proctoring alerts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.proctor_events (
    id            BIGSERIAL PRIMARY KEY,
    user_id       UUID    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type          TEXT    NOT NULL
        CHECK (type IN ('TAB_SWITCH', 'FULLSCREEN_EXIT', 'PASTE_BLOCKED', 'MULTI_SESSION', 'DISCONNECT')),
    severity      TEXT    NOT NULL CHECK (severity IN ('high', 'medium', 'low')),
    round_no      INTEGER NOT NULL DEFAULT 0,
    detail        TEXT    NOT NULL DEFAULT '',
    acknowledged  BOOLEAN NOT NULL DEFAULT FALSE,
    dismissed     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proctor_events_feed ON public.proctor_events(created_at DESC) WHERE NOT dismissed;
CREATE INDEX IF NOT EXISTS idx_proctor_events_user ON public.proctor_events(user_id, type, created_at DESC);

-- ---------------------------------------------------------------------------
-- 7. Row Level Security: deny by default; the backend (postgres role) bypasses it.
-- ---------------------------------------------------------------------------
ALTER TABLE public.event_config       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.languages          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.problems           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.problem_tests      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.participations     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.round_attempts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.distraction_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proctor_events     ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read event state" ON public.event_config;
CREATE POLICY "Authenticated can read event state"
    ON public.event_config FOR SELECT TO authenticated USING (TRUE);

-- Own-row read access (lets the client use Realtime on its own progress later without exposing others).
DROP POLICY IF EXISTS "Players can read own participation" ON public.participations;
CREATE POLICY "Players can read own participation"
    ON public.participations FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 8. Realtime: push event status changes (lobby -> live -> ended) to every connected client.
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.event_config;
EXCEPTION
    WHEN duplicate_object THEN null;
    WHEN undefined_object THEN null;
END $$;
